config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .views import TodoList, TodoDetail, TodoCreate, TodoDelete, TodoUpdate


urlpatterns = [
  path('list/', TodoList.as_view(), name='list'),
  path('detail/<int:pk>/', TodoDetail.as_view(), name='detail'),
  path('create/', TodoCreate.as_view(), name='create'),
  path('delete/<int:pk>', TodoDelete.as_view(), name='delete'),
  path('update/<int:pk>', TodoUpdate.as_view(), name='update')
]

todo/models.py
from django.db import models

CHOICE = (('danger', 'high'),('warning', 'normal'),('primary', 'low'))

class Todo(models.Model):
    title = models.CharField(max_length=200)
    memo = models.TextField()
    priority = models.CharField(
      max_length=50,
      choices = CHOICE
      )
    createdate = models.DateField()

    def __str__(self):
      return self.title

todo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Todo
from django.urls import reverse_lazy

class TodoList(ListView):
    template_name = 'list.html'
    model = Todo

class TodoDetail(DetailView):
    template_name = 'detail.html'
    model = Todo

class TodoCreate(CreateView):
    template_name = 'create.html'
    model = Todo
    fields = ('title', 'memo', 'priority', 'createdate')
    success_url = reverse_lazy('list')

class TodoDelete(DeleteView):
    template_name = 'delete.html'
    model = Todo
    success_url = reverse_lazy('list')

class TodoUpdate(UpdateView):
    template_name = 'update.html'
    model = Todo
    fields = ('title', 'memo', 'priority', 'createdate')
    success_url = reverse_lazy('list')

templates/base.html
<!-- 共通部分 -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Todoアプリ</title>
  </head>
  <body>

    {% block header %}
    {% endblock header%}

    {% block content %}
    {% endblock content %}
  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' value='create'>
</form>

<a href="{% url 'list' %}" class="btn btn-success mt-3" tabindex="-1" role="button" aria-disabled="true">戻る</a>
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='POST'>
  {% csrf_token %}
  <input type='submit' value='delete'>
</form>

<a href="{% url 'list' %}" class="btn btn-success mt-3" tabindex="-1" role="button" aria-disabled="true">戻る</a>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-dark" role="alert">
  detail
</div>
{% endblock header %}

{% block content %}
<div class="alert alert-success" role="alert">
  {{ object.title }}
</div>
<div class="alert alert-success" role="alert">
  {{ object.memo }}
</div>
<div class="alert alert-success" role="alert">
  優先度 {{ todo.get_priority_display }}
</div>
<div class="alert alert-success" role="alert">
  {{ object.createdate }}
</div>

<a href="{% url 'list' %}" class="btn btn-success mb-3" tabindex="-1" role="button" aria-disabled="true">戻る</a>

{% endblock content %}

templates/list.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-secondary fluid" role="alert">
  <div class="container">
    <h1 class="display-4">To-do-List</h1>
    <p class="lead">Todolistを作成して生産的な毎日を過ごしましょう</p>
  </div>
</div>
{% endblock header %}

{% block content %}
<div class="container">
  <a href="{% url 'create' %}" class="btn btn-success mb-3" tabindex="-1" role="button" aria-disabled="true">新規作成</a>
  {%for item in object_list %}
  <div class="alert alert-{{ item.priority }}" role="alert">
    <p>{{ item.title }} 期日: {{ item.createdate | date:"o/n/j "}}</p>
    <a href="{% url 'update' item.pk %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">編集画面</a>
    <a href="{% url 'delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除画面</a>
    <a href="{% url 'detail' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">詳細画面</a>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/update.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='POST'>
  {% csrf_token %}
  {{ form.as_ul }}
  <input type='submit' value='update'>
</form>

<a href="{% url 'list' %}" class="btn btn-success mt-3" tabindex="-1" role="button" aria-disabled="true">戻る</a>
{% endblock content %}